### ISSUE TITLE
Repurpose ipfs-block as a container for { data, cid }

### ISSUE THREAD

**Issue by kumavis** [ipfs/js-ipfs-block#25]
currently it is a wrapper around the data that adds a utility method for generating the multihash.

`block.key(hashFn, cb)` is not much better than `hash(hashFn, block.data, cb)`.

Instead I propose we repurpose this as a container around { data, cid } since that is not captured in a standard interface yet but use it in a number of places.

**Comment by daviddias** [comment]
Happening here: https://github.com/ipfs/js-ipfs-block/pull/31
