### ISSUE TITLE
Move to IPLD

### ISSUE THREAD

**Issue by mikeal** [ipfs/js-ipfs-block#43]
There's a discussion about [moving this concept/implementation to IPLD](https://github.com/ipld/ipld/issues/47#issuecomment-423114723).

Some questions specific to this implementation would be:

* Is the project willing to relocate to the IPLD org.
* Would we want to rename?
  * If we did rename how would be handle releases? Would we continue to release under both names or only the new name?

**Comment by vmx** [comment]
I would move it to IPLD, and rename it to `js-ipld-block`. Then update the dependents and deprecate js-ipfs-block.

As many modules depend on this one, I'd like to get a thumbs up/down from @diasdavid and @alanshaw.

**Comment by mikeal** [comment]
Any objections?

I’d like to do this soon if there are no objections.

Who handles the releases for this project?

**Comment by vmx** [comment]
No objections. The lead maintainer aka me does the releases.

**Comment by mikeal** [comment]
@vmx I moved the package to the org and renamed, would you mind renaming in the package.json and doing a new release?

**Comment by vmx** [comment]
@mikeal I don't have push access to this repo.

**Comment by alanshaw** [comment]
When this is updated can you please ensure that releases for modules that use it are major versions or minor versions for pre 1.0 modules. This will cause `Block.isBlock` comparisons to break (assuming you're going to [update the symbol name](https://github.com/ipld/js-ipld-block/blob/master/src/index.js#L57)).

**Comment by mikeal** [comment]
@vmx my bad, I added the JS team but it default to read access, upgrade to write, you should be good :)

**Comment by alanshaw** [comment]
Can be closed?

**Comment by vmx** [comment]
I guess it can be closed. I guess all modules using ipfs-block should upgrade to ipld-block, but that can be handled in separate issues.
