### ISSUE TITLE
Deprecate ipfs-block package

### ISSUE THREAD

**Issue by vmx** [ipfs/js-ipfs-block#49]
Once js-ipfs 0.36 has been released deprecate the ipfs-block package and make everyone upgrade to ipld-block.

```console
$ npm deprecate ipfs-block 'WARNING: This project has been renamed to "ipld-block". Install "ipld-block" instead.'
```

**Comment by rvagg** [comment]
closed for archival

@vmx: you could `npm deprecate ipld-block 'This project has been deprecated, see the multiformats package instead'
