### ISSUE TITLE
Allow passing Uint8Array data

### ISSUE THREAD

**Issue by Gozala** [ipfs/js-ipfs-block#52]
At the moment passing a block `Uint8Array` throws an exception

https://github.com/ipld/js-ipld-block/blob/7059cc8370e44cc9d9bc4ed73b3836acf38b0a05/src/index.js#L17-L21

I would like to propose a change that recognizes `Uint8Array` and if it is passed instead of throwing it creates a `Buffer` view for the same underlying `ArrayBuffer`

**Comment by vmx** [comment]
Fixed by https://github.com/ipld/js-ipld-block/pull/53.

**Comment by hugomrdias** [comment]
should this be closed ?
